services:
  app.static_content_extension:
        class: StaticContentBundle\Twig\StaticContentExtension
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@club_manager"
        tags:
          - { name: twig.extension }
