#Course
cp_course:
  path: /kurs
  defaults: {_controller: CourseBundle:AdminCourse:show}

cp_create_course:
  path: /kurs/ny
  defaults: {_controller: CourseBundle:AdminCourse:editCourse}

cp_edit_course:
  path: /kurs/{id}
  defaults: {_controller: CourseBundle:AdminCourse:editCourse}
  requirements:
    id: \d+

cp_delete_course:
  path: /kurs/slett/{id}
  defaults: {_controller: CourseBundle:AdminCourse:deleteCourse}
  requirements:
    id: \d+

cp_course_participants:
  path: /kurs/deltakere/{id}
  defaults: {_controller: CourseBundle:AdminCourse:showParticipants}
  requirements:
    id: \d+

cp_course_tutors:
  path: /kurs/veiledere/{id}
  defaults: {_controller: CourseBundle:AdminCourse:showTutors}
  requirements:
    id: \d+

#Course type
cp_course_type:
  path: /kurs/type
  defaults: {_controller: CourseBundle:AdminCourseType:show}

cp_edit_course_type:
  path: /kurs/type/{id}
  defaults: {_controller: CourseBundle:AdminCourseType:editCourseType}
  requirements:
    id: \d+

cp_create_course_type:
  path: /kurs/type/ny
  defaults: {_controller: CourseBundle:AdminCourseType:editCourseType}

cp_delete_course_type:
  path: /kurs/type/slett/{id}
  defaults: {_controller: CourseBundle:AdminCourseType:deleteCourseType}
  requirements:
    id: \d+

#Course class
cp_course_time_table:
  path: /kurs/timeplan/{id}
  defaults: {_controller: CourseBundle:AdminCourse:editTimeTable}
  requirements:
    id: \d+

cp_delete_course_class:
  path: /kontrollpanel/kursdag/slett/{id}
  defaults: {_controller: CourseBundle:AdminCourse:deleteCourseClass}
  requirements:
    id: \d+

#Sign up
cp_sign_up:
  path: /pamelding/{id}
  defaults: {_controller: CourseBundle:AdminSignUp:show}

cp_sign_up_course:
  path: /pamelding/{course}/{user}
  defaults: {_controller: CourseBundle:AdminSignUp:signUp}
  requirements:
    id: \d+
  methods: [POST]

cp_sign_up_course_child:
  path: /pamelding/barn/{id}/{child}
  defaults: {_controller: CourseBundle:AdminSignUp:signUpChild}
  requirements:
    id: \d+
  options:
    expose: true
