control_panel_course:
    resource: "./cp_routing.yml"
    prefix: /kontrollpanel

courses:
  path: /kurs
  defaults: {_controller: CourseBundle:Course:show}

course_info:
  path: /kurs/{id}
  defaults: {_controller: CourseBundle:Course:showCourseInfo}
  requirements:
    id: \d+

#Sign up
sign_up:
  path: /pamelding
  defaults: {_controller: CourseBundle:SignUp:show}

sign_up_course:
  path: /pamelding/{id}
  defaults: {_controller: CourseBundle:SignUp:signUp}
  requirements:
    id: \d+

sign_up_course_child:
  path: /pamelding/barn/{id}/{child}
  defaults: {_controller: CourseBundle:SignUp:signUpChild}
  requirements:
    id: \d+
  options:
    expose: true

withdraw_from_course_tutor:
  path: /pamelding/veileder/meldav/{courseId}/{tutorId}
  defaults: {_controller: CourseBundle:SignUp:withdrawTutor, tutorId: null}
  requirements:
    courseId: \d+
    tutorId: \d+

withdraw_from_course_participant:
  path: /pamelding/deltaker/meldav/{id}
  defaults: {_controller: CourseBundle:SignUp:withdrawParticipant}
  requirements:
    id: \d+