services:
    course.sign_up:
        class: CourseBundle\Service\SignUp
    twig.extension.sign_up:
        class: CourseBundle\Twig\SignupExtension
        tags:
            - { name: twig.extension }
