services:
    course.sign_up:
        class: CourseBundle\Service\SignUp

    course.queue_manager:
        class: CourseBundle\Service\CourseQueueManager
        arguments: ['@doctrine.orm.default_entity_manager', '@app.notification_manager']

    course.manager:
        class: CourseBundle\Service\CourseManager

    course.queue_subscriber:
        class: CourseBundle\EventSubscriber\CourseQueueSubscriber
        arguments: ['@course.queue_manager', '@logger']
        tags:
          - { name: kernel.event_subscriber }

    twig.extension.sign_up:
        class: CourseBundle\Twig\SignupExtension
        tags:
            - { name: twig.extension }
