image:
    resource: '@ImageBundle/Controller/'
    type:     annotation

user:
    resource: '@UserBundle/Controller/'
    type:     annotation

course:
    resource: '@CourseBundle/Controller/'
    type:     annotation

static_content:
    resource: '@StaticContentBundle/Controller/'
    type:     annotation

admin:
    resource: '@AdminBundle/Controller/'
    type:     annotation

code_club:
    resource: '@CodeClubBundle/Controller/'
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#Security
security_login_form:
    path: /login/{last_username}
    defaults: {_controller: CodeClubBundle:Security:login, last_username: ''}

security_login_check:
    path: /login_check
    defaults: {_controller: CodeClubBundle:Security:loginCheck}

security_logout:
    path: /logout
    defaults: {_controller: CodeClubBundle:Security:logout}

password_reset:
  path: /reset_passord
  defaults: {_controller: UserBundle:PasswordReset:show}

password_new:
  path: /reset_passord/{code}
  defaults: {_controller: UserBundle:PasswordReset:resetPassword}