user:
    resource: "@UserBundle/Resources/config/routing.yml"

course:
    resource: "@CourseBundle/Resources/config/routing.yml"

static_content:
    resource: "@StaticContentBundle/Resources/config/routing.yml"

code_club_generator:
    resource: "@CodeClubGeneratorBundle/Resources/config/routing.yml"
    prefix:   /generator

code_club_admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /kontrollpanel

code_club:
    resource: "@CodeClubBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#Security
security_login_form:
    path: /login
    defaults: {_controller: CodeClubBundle:Security:login}

security_login_check:
    path: /login_check
    defaults: {_controller: CodeClubBundle:Security:loginCheck}

security_logout:
    path: /logout
    defaults: {_controller: CodeClubBundle:Security:logout}

password_reset:
  path: /reset_passord
  defaults: {_controller: UserBundle:PasswordReset:show}

password_new:
  path: /reset_passord/{code}
  defaults: {_controller: UserBundle:PasswordReset:resetPassword}