#code_club_homepage:
#    path:     /
#    defaults: { _controller: CodeClubBundle:Default:index }

#Pages
home:
  path: /
  defaults: {_controller: CodeClubBundle:Home:show}

about:
  path: /om
  defaults: {_controller: CodeClubBundle:About:show}

api_get_course_classes_by_week:
  path: /api/kurs/uke/{week}
  defaults: {_controller: CourseBundle:Course:getCourseClasses}
  requirements:
    week: \d+






