services:
    app.twig_code_club_extension:
        class: CodeClubBundle\Twig\CodeClubExtension
        arguments:
            - "@club_manager"
        tags:
            - { name: twig.extension }
    club_manager:
        class: CodeClubBundle\Service\ClubManager
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@request_stack"
    club_registration:
        class: CodeClubBundle\Service\ClubRegistration
        arguments:
            - "@mailer"
            - "@router"
            - "@user.registration"
            - "%base_host%"
            - "%default_mail%"
