services:
  app.twig_code_club_extension:
      class: CodeClubBundle\Twig\CodeClubExtension
      arguments:
        doctrine: "@doctrine"
        container: "@router"
      tags:
        - { name: twig.extension }
