services:
  app.twig_code_club_extension:
      class: CodeClubBundle\Twig\CodeClubExtension
      arguments:
        doctrine: "@doctrine"
        clubFinder: "@app.club_finder"
      tags:
        - { name: twig.extension }
  app.club_finder:
        class: CodeClubBundle\Service\ClubFinder
        arguments:
          doctrine: "@doctrine"
          container: "@router"
