#Users
cp_user:
  path: /brukere/{id}
  defaults: {_controller: UserBundle:AdminUser:showSpecific}

cp_users:
  path: /brukere
  defaults: {_controller: UserBundle:AdminUser:show}

cp_change_user_type:
  path: /bruker/type
  defaults: {_controller: UserBundle:User:changeUserType}
  methods: [POST]
  options:
    expose: true

cp_user_delete:
  path: /buker/slett
  defaults: {_controller: UserBundle:User:delete}
  methods: [POST]
  options:
    expose: true

cp_user_create:
  path: /bruker/ny
  defaults: {_controller: UserBundle:AdminUser:createUser}

#Child
cp_child_create:
  path: /barn/ny/{user}
  defaults: {_controller: UserBundle:Child:adminCreateChild}
