services:
  user.registration:
    class: UserBundle\Service\UserRegistration
    arguments: ['@security.password_encoder', '@doctrine.orm.default_entity_manager', '@club_manager', '@twig', '@mailer']

  user.roles:
    class: UserBundle\Service\UserRoles
    arguments: ['%security.role_hierarchy.roles%']

  user.twig_user_role_filter:
    class: UserBundle\Twig\UserExtension
    public: false
    tags:
      - { name: twig.extension }
