services:
  user.registration:
    class: UserBundle\Service\UserRegistration
    arguments: ['@security.password_encoder', '@doctrine', '@app.club_finder', '@twig', '@mailer']

  user.roles:
    class: UserBundle\Service\UserRoles
    arguments: ['%security.role_hierarchy.roles%']

