#Control Panel
control_panel:
  path: /
  defaults: {_controller: CodeClubAdminBundle:ControlPanel:show}

cp_email:
  path: /epost
  defaults: {_controller: CodeClubAdminBundle:ControlPanel:showEmail}

cp_message:
  path: /melding
  defaults: {_controller: CodeClubAdminBundle:Message:show}

cp_delete_message:
  path: /melding/slett/{id}
  defaults: {_controller: CodeClubAdminBundle:Message:deleteMessage}
  requirements:
    id: \d+

cp_tutors:
  path: /veiledere
  defaults: {_controller: CodeClubAdminBundle:ControlPanel:showTutors}

cp_participants:
  path: /deltakere
  defaults: {_controller: CodeClubAdminBundle:ControlPanel:showParticipants}

