#Control Panel
control_panel:
  path: /
  defaults: {_controller: CodeClubAdminBundle:ControlPanel:show}

cp_email:
  path: /epost
  defaults: {_controller: CodeClubAdminBundle:ControlPanel:showEmail}

cp_message:
  path: /melding
  defaults: {_controller: CodeClubAdminBundle:Message:show}

cp_delete_message:
  path: /melding/slett/{id}
  defaults: {_controller: CodeClubAdminBundle:Message:deleteMessage}
  requirements:
    id: \d+

cp_sc_header:
  path: /statisk_innhold/header
  defaults: {_controller: CodeClubAdminBundle:StaticContent:showHeader}

cp_sc_tagline:
  path: /statisk_innhold/tagline
  defaults: {_controller: CodeClubAdminBundle:StaticContent:showTagline}

cp_sc_participant_info:
  path: /statisk_innhold/deltaker
  defaults: {_controller: CodeClubAdminBundle:StaticContent:showParticipant}

cp_sc_tutor_info:
  path: /statisk_innhold/veileder
  defaults: {_controller: CodeClubAdminBundle:StaticContent:showTutor}

cp_sc_about:
  path: /statisk_innhold/om
  defaults: {_controller: CodeClubAdminBundle:StaticContent:showAbout}

cp_update_static_content:
  path: /statisk_innhold
  defaults: {_controller: StaticContentBundle:StaticContent:update}
  methods: [POST]
  options:
    expose: true

cp_info:
  path: /info
  defaults: {_controller: CodeClubAdminBundle:StaticContent:showInfo}

cp_tutors:
  path: /veiledere
  defaults: {_controller: CodeClubAdminBundle:ControlPanel:showTutors}

cp_participants:
  path: /deltakere
  defaults: {_controller: CodeClubAdminBundle:ControlPanel:showParticipants}

cp_users:
  path: /brukere
  defaults: {_controller: CodeClubAdminBundle:User:show}

cp_change_user_type:
  path: /bruker/type
  defaults: {_controller: CodeClubBundle:User:changeUserType}
  methods: [POST]
  options:
    expose: true

cp_user_delete:
  path: /buker/slett
  defaults: {_controller: CodeClubBundle:User:delete}
  methods: [POST]
  options:
    expose: true


cp_course_participants:
  path: /kurs/deltakere/{id}
  defaults: {_controller: CodeClubAdminBundle:Course:showParticipants}
  requirements:
    id: \d+

cp_course_tutors:
  path: /kurs/veiledere/{id}
  defaults: {_controller: CodeClubAdminBundle:Course:showTutors}
  requirements:
    id: \d+

cp_course_type:
  path: /kurs/type
  defaults: {_controller: CodeClubAdminBundle:CourseType:show}

cp_edit_course_type:
  path: /kurs/type/{id}
  defaults: {_controller: CodeClubAdminBundle:CourseType:editCourseType}
  requirements:
    id: \d+

cp_create_course_type:
  path: /kurs/type/ny
  defaults: {_controller: CodeClubAdminBundle:CourseType:editCourseType}

cp_delete_course_type:
  path: /kurs/type/slett/{id}
  defaults: {_controller: CodeClubAdminBundle:CourseType:deleteCourseType}
  requirements:
    id: \d+

cp_course:
  path: /kurs
  defaults: {_controller: CodeClubAdminBundle:Course:show}

cp_create_course:
  path: /kurs/ny
  defaults: {_controller: CodeClubAdminBundle:Course:editCourse}

cp_edit_course:
  path: /kurs/{id}
  defaults: {_controller: CodeClubAdminBundle:Course:editCourse}
  requirements:
    id: \d+

cp_delete_course:
  path: /kurs/slett/{id}
  defaults: {_controller: CodeClubAdminBundle:Course:deleteCourse}
  requirements:
    id: \d+

cp_course_time_table:
  path: /kurs/timeplan/{id}
  defaults: {_controller: CodeClubAdminBundle:Course:editTimeTable}
  requirements:
    id: \d+


cp_delete_course_class:
  path: /kontrollpanel/kursdag/slett/{id}
  defaults: {_controller: CodeClubAdminBundle:Course:deleteCourseClass}
  requirements:
    id: \d+